// BASE DE DATOS COMPLETA DE VEHÍCULOS WAR THUNDER - VERSIÓN CORREGIDA
const vehiclesDatabase = [
    // ========== USA ==========
    {
        id: 1,
        name: "M1A2 Abrams",
        type: "tanque",
        nation: "usa",
        br: 11.7,
        era: "VII",
        crew: 4,
        armor: "Chobham/Dorchester",
        mainGun: "120mm M256",
        penetration: "480mm M829A2",
        engine: "AGT-1500 1500hp",
        speed: 67,
        weight: 63.0,
        year: 1992,
        characteristics: ["TI CITV", "Estabilizador completo", "Munición M829A2", "Sistema FBCB2"]
    },
    {
        id: 2,
        name: "M1A1 HC",
        type: "tanque",
        nation: "usa",
        br: 10.7,
        era: "VII",
        crew: 4,
        armor: "Chobham con uranio",
        mainGun: "120mm M256",
        penetration: "430mm M829",
        engine: "AGT-1500 1500hp",
        speed: 67,
        weight: 61.5,
        year: 1988,
        characteristics: ["Armadura DU", "TI mejorado", "Sistema NBC"]
    },
    {
        id: 3,
        name: "M60A3 TTS",
        type: "tanque",
        nation: "usa",
        br: 8.7,
        era: "VI",
        crew: 4,
        armor: "Acero homogéneo",
        mainGun: "105mm M68",
        penetration: "350mm M735",
        engine: "AVDS-1790-2C 750hp",
        speed: 48,
        weight: 52.6,
        year: 1979,
        characteristics: ["TI TTS", "Laser rangefinder", "Estabilizador"]
    },
    {
        id: 4,
        name: "M4A3E2 Sherman Jumbo",
        type: "tanque",
        nation: "usa",
        br: 5.7,
        era: "III",
        crew: 5,
        armor: "Acero 101mm frontal",
        mainGun: "75mm M3",
        penetration: "110mm M61",
        engine: "Ford GAA 450hp",
        speed: 35,
        weight: 38.1,
        year: 1944,
        characteristics: ["Blindaje pesado", "Cañón corto 75mm", "Perfil bajo"]
    },
    {
        id: 5,
        name: "F-16C Fighting Falcon",
        type: "avion",
        nation: "usa",
        br: 12.3,
        era: "VIII",
        crew: 1,
        armor: "Aluminio + Composite",
        mainGun: "20mm M61A1 Vulcan",
        penetration: "N/A",
        engine: "F110-GE-100 x1",
        speed: 2120,
        weight: 19.7,
        year: 1984,
        characteristics: ["Radio AN/APG-68", "Misiles AMRAAM", "Sistema FLIR", "9G capacidad"]
    },
    {
        id: 6,
        name: "F-14B Tomcat",
        type: "avion",
        nation: "usa",
        br: 12.0,
        era: "VIII",
        crew: 2,
        armor: "Titanio + Aluminio",
        mainGun: "20mm M61A1 Vulcan",
        penetration: "N/A",
        engine: "F110-GE-400 x2",
        speed: 2485,
        weight: 33.7,
        year: 1987,
        characteristics: ["Radar AWG-9", "Misiles Phoenix", "Alas variables", "TWS avanzado"]
    },
    {
        id: 7,
        name: "A-10A Thunderbolt II",
        type: "avion",
        nation: "usa",
        br: 10.0,
        era: "VI",
        crew: 1,
        armor: "Bañera de titanio",
        mainGun: "30mm GAU-8/A Avenger",
        penetration: "69mm RHA a 1000m",
        engine: "TF34-GE-100 x2",
        speed: 706,
        weight: 23.0,
        year: 1975,
        characteristics: ["GAU-8 Avenger", "TI Pave Penny", "11 puntos duros", "Resistente a daños"]
    },
    {
        id: 8,
        name: "P-51D-30 Mustang",
        type: "avion",
        nation: "usa",
        br: 5.3,
        era: "IV",
        crew: 1,
        armor: "Acero blindado",
        mainGun: "6x 12.7mm M2 Browning",
        penetration: "N/A",
        engine: "Packard V-1650-7 1490hp",
        speed: 703,
        weight: 5.0,
        year: 1944,
        characteristics: ["Alas laminates", "Motor Merlin", "Buenas características a alta altitud"]
    },
    {
        id: 9,
        name: "AH-64D Apache",
        type: "helicoptero",
        nation: "usa",
        br: 11.3,
        era: "VII",
        crew: 2,
        armor: "Kevlar + Composite",
        mainGun: "30mm M230 Chain Gun",
        penetration: "N/A",
        engine: "T700-GE-701C x2",
        speed: 365,
        weight: 10.5,
        year: 1997,
        characteristics: ["Radar Longbow", "Misiles Hellfire", "FLIR TADS/PNVS", "16 Hellfires"]
    },
    {
        id: 10,
        name: "UH-1B Iroquois",
        type: "helicoptero",
        nation: "usa",
        br: 8.0,
        era: "V",
        crew: 4,
        armor: "Asientos blindados",
        mainGun: "2x 7.62mm M134 Minigun",
        penetration: "N/A",
        engine: "Lycoming T53-L-11 1100hp",
        speed: 220,
        weight: 4.3,
        year: 1963,
        characteristics: ["Miniguns flexibles", "Rockets FFAR", "Capacidad tropas"]
    },

    // ========== URSS ==========
    {
        id: 11,
        name: "T-80BVM",
        type: "tanque",
        nation: "urss",
        br: 11.7,
        era: "VII",
        crew: 3,
        armor: "Composite + Relikt ERA",
        mainGun: "125mm 2A46M-4",
        penetration: "500mm 3BM60",
        engine: "GTD-1250 1250hp",
        speed: 70,
        weight: 46.0,
        year: 2017,
        characteristics: ["ERA Relikt", "TI Sosna-U", "Motor turbina", "Shtora-1"]
    },
    {
        id: 12,
        name: "T-72B3",
        type: "tanque",
        nation: "urss",
        br: 11.3,
        era: "VII",
        crew: 3,
        armor: "Composite + Kontakt-5",
        mainGun: "125mm 2A46M-5",
        penetration: "480mm 3BM42",
        engine: "V-84-1 840hp",
        speed: 60,
        weight: 46.0,
        year: 2010,
        characteristics: ["ERA Kontakt-5", "Estabilizador 2E42-4", "TI Sosna-U"]
    },
    {
        id: 13,
        name: "T-64B",
        type: "tanque",
        nation: "urss",
        br: 9.7,
        era: "VI",
        crew: 3,
        armor: "Composite + Fibra de vidrio",
        mainGun: "125mm 2A46-2",
        penetration: "450mm 3BM42",
        engine: "5TDF 700hp",
        speed: 60,
        weight: 39.0,
        year: 1976,
        characteristics: ["Primer MBT soviético", "Cargador automático", "Misiles Kobra"]
    },
    {
        id: 14,
        name: "T-34-85",
        type: "tanque",
        nation: "urss",
        br: 5.7,
        era: "III",
        crew: 5,
        armor: "Acero 45mm frontal",
        mainGun: "85mm ZiS-S-53",
        penetration: "120mm BR-365A",
        engine: "V-2-34 500hp",
        speed: 55,
        weight: 32.0,
        year: 1944,
        characteristics: ["Blindaje inclinado", "Buena movilidad", "Cañón 85mm efectivo"]
    },
    {
        id: 15,
        name: "MiG-29SMT",
        type: "avion",
        nation: "urss",
        br: 12.7,
        era: "VIII",
        crew: 1,
        armor: "Aluminio + Aleaciones",
        mainGun: "30mm GSh-30-1",
        penetration: "N/A",
        engine: "RD-33 series 3 x2",
        speed: 2450,
        weight: 18.5,
        year: 2000,
        characteristics: ["Radar N019ME", "R-77 AMRAAMski", "Tanques conformados", "IRST OEPS-29"]
    },
    {
        id: 16,
        name: "Su-27 Flanker",
        type: "avion",
        nation: "urss",
        br: 12.3,
        era: "VIII",
        crew: 1,
        armor: "Titanio + Aluminio",
        mainGun: "30mm GSh-30-1",
        penetration: "N/A",
        engine: "AL-31F x2",
        speed: 2500,
        weight: 23.0,
        year: 1984,
        characteristics: ["Excelente maniobrabilidad", "Radar N001", "Misiles R-27", "Ala de combate"]
    },
    {
        id: 17,
        name: "IL-2 Sturmovik",
        type: "avion",
        nation: "urss",
        br: 3.3,
        era: "II",
        crew: 2,
        armor: "Bañera blindada",
        mainGun: "2x 23mm VYa-23",
        penetration: "N/A",
        engine: "AM-38F 1720hp",
        speed: 414,
        weight: 6.3,
        year: 1942,
        characteristics: ["Blindaje pesado", "Rockets RS-82", "Buen ataque a tierra"]
    },
    {
        id: 18,
        name: "Ka-52 Alligator",
        type: "helicoptero",
        nation: "urss",
        br: 11.3,
        era: "VII",
        crew: 2,
        armor: "Blindaje integrado",
        mainGun: "30mm 2A42",
        penetration: "N/A",
        engine: "VK-2500 x2",
        speed: 350,
        weight: 10.4,
        year: 1995,
        characteristics: ["Rotor coaxial", "Misiles Vikhr", "Radar Arbalet", "Eyectores flares"]
    },
    {
        id: 19,
        name: "Mi-24V Hind-E",
        type: "helicoptero",
        nation: "urss",
        br: 10.3,
        era: "VI",
        crew: 3,
        armor: "Titanio + Vidrio blindado",
        mainGun: "12.7mm YakB-12.7",
        penetration: "N/A",
        engine: "TV3-117 x2",
        speed: 335,
        weight: 8.5,
        year: 1974,
        characteristics: ["Transporte + ataque", "Misiles AT-6 Spiral", "Rockets S-8"]
    },

    // ========== ALEMANIA ==========
    {
        id: 20,
        name: "Leopard 2A6",
        type: "tanque",
        nation: "alemania",
        br: 11.7,
        era: "VII",
        crew: 4,
        armor: "Composite + Espaciada",
        mainGun: "120mm L/55",
        penetration: "510mm DM53",
        engine: "MTU MB-873 1500hp",
        speed: 68,
        weight: 62.0,
        year: 2001,
        characteristics: ["Cañón L/55", "TI WBG-X", "Sistema PERI R17A2", "Munición DM53"]
    },
    {
        id: 21,
        name: "Leopard 2A5",
        type: "tanque",
        nation: "alemania",
        br: 11.3,
        era: "VII",
        crew: 4,
        armor: "Composite mejorado",
        mainGun: "120mm L/44",
        penetration: "480mm DM33",
        engine: "MTU MB-873 1500hp",
        speed: 68,
        weight: 59.5,
        year: 1995,
        characteristics: ["Cuña frontal", "TI mejorado", "Sistema de visión independiente"]
    },
    {
        id: 22,
        name: "Leopard 1",
        type: "tanque",
        nation: "alemania",
        br: 7.3,
        era: "V",
        crew: 4,
        armor: "Acero 70mm",
        mainGun: "105mm L7A3",
        penetration: "390mm DM23",
        engine: "MTU MB-838 830hp",
        speed: 65,
        weight: 42.5,
        year: 1965,
        characteristics: ["Excelente movilidad", "Cañón L7 preciso", "Blindaje ligero"]
    },
    {
        id: 23,
        name: "Tiger II (H)",
        type: "tanque",
        nation: "alemania",
        br: 6.7,
        era: "IV",
        crew: 5,
        armor: "Acero 185mm frontal",
        mainGun: "88mm KwK 43",
        penetration: "237mm PzGr 39/43",
        engine: "Maybach HL 230 700hp",
        speed: 38,
        weight: 69.8,
        year: 1944,
        characteristics: ["Blindaje pesado", "Cañón 88mm poderoso", "Movilidad limitada"]
    },
    {
        id: 24,
        name: "Eurofighter Typhoon",
        type: "avion",
        nation: "alemania",
        br: 12.7,
        era: "VIII",
        crew: 1,
        armor: "Composite + Aleaciones",
        mainGun: "27mm Mauser BK-27",
        penetration: "N/A",
        engine: "EJ200 x2",
        speed: 2495,
        weight: 16.0,
        year: 2003,
        characteristics: ["Canard delta", "Radar Captor-M", "Misiles Meteor", "TVC"]
    },
    {
        id: 25,
        name: "MiG-29G",
        type: "avion",
        nation: "alemania",
        br: 12.3,
        era: "VIII",
        crew: 1,
        armor: "Aluminio + Aleaciones",
        mainGun: "30mm GSh-30-1",
        penetration: "N/A",
        engine: "RD-33 x2",
        speed: 2450,
        weight: 18.0,
        year: 1990,
        characteristics: ["Versión alemana", "Aviónica occidental", "IRST OEPS-29"]
    },
    {
        id: 26,
        name: "Fw 190 D-9",
        type: "avion",
        nation: "alemania",
        br: 5.7,
        era: "IV",
        crew: 1,
        armor: "Acero blindado",
        mainGun: "2x 20mm MG 151/20",
        penetration: "N/A",
        engine: "Junkers Jumo 213A 1776hp",
        speed: 685,
        weight: 4.3,
        year: 1944,
        characteristics: ["Motor en línea", "Excelente trepada", "Buen desempeño a alta altitud"]
    },
    {
        id: 27,
        name: "Tiger UHT",
        type: "helicoptero",
        nation: "alemania",
        br: 11.7,
        era: "VII",
        crew: 2,
        armor: "Composite + Kevlar",
        mainGun: "12.7mm MG3",
        penetration: "N/A",
        engine: "MTU MTR390 x2",
        speed: 315,
        weight: 6.0,
        year: 1990,
        characteristics: ["Misiles PARS 3 LR", "Sistema de adquisición", "Rotor rígido"]
    },

    // ========== REINO UNIDO ==========
    {
        id: 28,
        name: "Challenger 2",
        type: "tanque",
        nation: "uk",
        br: 11.7,
        era: "VII",
        crew: 4,
        armor: "Chobham 2nd Gen",
        mainGun: "120mm L30A1",
        penetration: "480mm L26A1",
        engine: "Perkins CV12 1200hp",
        speed: 59,
        weight: 62.5,
        year: 1998,
        characteristics: ["Armadura Dorchester", "Cañón estriado", "Sistema TOGS", "Munición HESH"]
    },
    {
        id: 29,
        name: "Challenger 1",
        type: "tanque",
        nation: "uk",
        br: 10.3,
        era: "VII",
        crew: 4,
        armor: "Chobham",
        mainGun: "120mm L11A5",
        penetration: "430mm L23A1",
        engine: "Perkins CV12 1200hp",
        speed: 59,
        weight: 62.0,
        year: 1983,
        characteristics: ["Primer Chobham UK", "Sistema TOGS", "Buena protección"]
    },
    {
        id: 30,
        name: "Centurion Mk.10",
        type: "tanque",
        nation: "uk",
        br: 7.7,
        era: "V",
        crew: 4,
        armor: "Acero + Espaciada",
        mainGun: "105mm L7A1",
        penetration: "390mm APDS",
        engine: "Rolls-Royce Meteor 650hp",
        speed: 35,
        weight: 52.0,
        year: 1955,
        characteristics: ["Cañón L7", "Blindaje inclinado", "Estabilizador 2-plano"]
    },
    {
        id: 31,
        name: "Spitfire LF Mk.IX",
        type: "avion",
        nation: "uk",
        br: 5.3,
        era: "IV",
        crew: 1,
        armor: "Acero blindado",
        mainGun: "2x 20mm Hispano Mk.II",
        penetration: "N/A",
        engine: "Rolls-Royce Merlin 66 1720hp",
        speed: 650,
        weight: 3.5,
        year: 1943,
        characteristics: ["Ala elíptica", "Excelente maniobrabilidad", "Motor Merlin"]
    },
    {
        id: 32,
        name: "Harrier GR.7",
        type: "avion",
        nation: "uk",
        br: 11.3,
        era: "VII",
        crew: 1,
        armor: "Aluminio + Composite",
        mainGun: "2x 25mm ADEN",
        penetration: "N/A",
        engine: "Rolls-Royce Pegasus 103",
        speed: 1065,
        weight: 14.0,
        year: 1989,
        characteristics: ["VTOL/STOL", "TI FLIR", "Misiles Brimstone", "Rockets CRV7"]
    },

    // ========== JAPÓN ==========
    {
        id: 33,
        name: "Type 10",
        type: "tanque",
        nation: "japon",
        br: 11.7,
        era: "VII",
        crew: 3,
        armor: "Composite modular",
        mainGun: "120mm L44",
        penetration: "520mm JM33",
        engine: "V8 1200hp",
        speed: 70,
        weight: 44.0,
        year: 2012,
        characteristics: ["Sistema C4I", "Suspensión hidroneumática", "TI avanzado", "Peso variable"]
    },
    {
        id: 34,
        name: "Type 90",
        type: "tanque",
        nation: "japon",
        br: 11.0,
        era: "VII",
        crew: 3,
        armor: "Composite cerámico",
        mainGun: "120mm L44",
        penetration: "480mm JM33",
        engine: "Mitsubishi 10ZG 1500hp",
        speed: 70,
        weight: 50.0,
        year: 1990,
        characteristics: ["Cargador automático", "Suspensión hidroneumática", "TI termal"]
    },
    {
        id: 35,
        name: "ST-A3",
        type: "tanque",
        nation: "japon",
        br: 6.7,
        era: "V",
        crew: 4,
        armor: "Acero 45mm",
        mainGun: "90mm Type 61",
        penetration: "220mm APHE",
        engine: "Mitsubishi 12HM21WT 570hp",
        speed: 45,
        weight: 35.0,
        year: 1957,
        characteristics: ["Primer diseño post-guerra", "Hidropneumático", "Cañón 90mm"]
    },
    {
        id: 36,
        name: "A6M5 Zero",
        type: "avion",
        nation: "japon",
        br: 4.7,
        era: "III",
        crew: 1,
        armor: "Sin blindaje",
        mainGun: "2x 20mm Type 99-2",
        penetration: "N/A",
        engine: "Nakajima NK1F 1130hp",
        speed: 565,
        weight: 2.8,
        year: 1943,
        characteristics: ["Maniobrabilidad extrema", "Alcance largo", "Sin blindaje", "Armamento ligero"]
    },
    {
        id: 37,
        name: "F-4EJ Kai Phantom II",
        type: "avion",
        nation: "japon",
        br: 11.3,
        era: "VII",
        crew: 2,
        armor: "Aluminio + Titanio",
        mainGun: "20mm JM61A1 Vulcan",
        penetration: "N/A",
        engine: "GE J79-IHI-17 x2",
        speed: 2390,
        weight: 28.0,
        year: 1984,
        characteristics: ["Radar J/AWG-11", "Misiles AAM-3", "Sistema de contramedidas"]
    },

    // ========== FRANCIA ==========
    {
        id: 38,
        name: "Leclerc SXXI",
        type: "tanque",
        nation: "francia",
        br: 11.7,
        era: "VII",
        crew: 3,
        armor: "Composite modular",
        mainGun: "120mm CN120-26",
        penetration: "540mm OFL 120 F2",
        engine: "SACM V8X 1500hp",
        speed: 72,
        weight: 56.5,
        year: 2003,
        characteristics: ["Cargador automático", "Sistema FINDERS", "TI Iris", "Autocargador 5rpm"]
    },
    {
        id: 39,
        name: "AMX-40",
        type: "tanque",
        nation: "francia",
        br: 10.3,
        era: "VI",
        crew: 4,
        armor: "Composite espaciado",
        mainGun: "120mm CN120-26",
        penetration: "400mm OFL 120 G1",
        engine: "Poyaud V12 1300hp",
        speed: 70,
        weight: 43.7,
        year: 1985,
        characteristics: ["Movilidad excelente", "Cañón 120mm", "Blindaje ligero"]
    },
    {
        id: 40,
        name: "Mirage 2000-5F",
        type: "avion",
        nation: "francia",
        br: 12.7,
        era: "VIII",
        crew: 1,
        armor: "Aleaciones ligeras",
        mainGun: "2x 30mm DEFA 554",
        penetration: "N/A",
        engine: "SNECMA M53-P2",
        speed: 2495,
        weight: 17.5,
        year: 2000,
        characteristics: ["Ala delta", "Radar RDY", "Misiles MICA", "Excelente energía"]
    },

    // ========== ITALIA ==========
    {
        id: 41,
        name: "Ariete AMV",
        type: "tanque",
        nation: "italia",
        br: 11.3,
        era: "VII",
        crew: 4,
        armor: "Composite tungsteno",
        mainGun: "120mm L/44",
        penetration: "450mm DM33",
        engine: "IVECO V12 MTCA 1500hp",
        speed: 65,
        weight: 54.0,
        year: 2018,
        characteristics: ["Armadura WAR", "Sistema TURMS", "Movilidad buena"]
    },
    {
        id: 42,
        name: "Centauro 120",
        type: "tanque",
        nation: "italia",
        br: 9.3,
        era: "VI",
        crew: 4,
        armor: "Aluminio + Acero",
        mainGun: "120mm L/45",
        penetration: "400mm APFSDS",
        engine: "IVECO V6 520hp",
        speed: 110,
        weight: 30.0,
        year: 2002,
        characteristics: ["Ruedas 8x8", "Movilidad excelente", "Cañón 120mm", "Reconocimiento"]
    },
    {
        id: 43,
        name: "F-104S ASA",
        type: "avion",
        nation: "italia",
        br: 11.0,
        era: "VII",
        crew: 1,
        armor: "Aluminio",
        mainGun: "20mm M61A1 Vulcan",
        penetration: "N/A",
        engine: "GE J79-GE-19",
        speed: 2330,
        weight: 14.0,
        year: 1985,
        characteristics: ["Misiles Aspide", "Radar R21G", "Alas pequeñas", "Aceleración rápida"]
    },

    // ========== CHINA ==========
    {
        id: 44,
        name: "ZTZ99A",
        type: "tanque",
        nation: "china",
        br: 11.7,
        era: "VII",
        crew: 3,
        armor: "Composite + ERA",
        mainGun: "125mm ZPT-98",
        penetration: "500mm DTC10-125",
        engine: "150HB 1500hp",
        speed: 70,
        weight: 55.0,
        year: 2011,
        characteristics: ["ERA FY-4", "Laser dazzler", "TI avanzado", "Cargador automático"]
    },
    {
        id: 45,
        name: "Type 96A",
        type: "tanque",
        nation: "china",
        br: 9.7,
        era: "VI",
        crew: 3,
        armor: "Composite + ERA",
        mainGun: "125mm ZPT-98",
        penetration: "440mm DTC10-125",
        engine: "12150ZL 780hp",
        speed: 65,
        weight: 41.5,
        year: 2005,
        characteristics: ["ERA FY-4", "TI básico", "Cargador automático"]
    },
    {
        id: 46,
        name: "J-8F",
        type: "avion",
        nation: "china",
        br: 11.7,
        era: "VIII",
        crew: 1,
        armor: "Aleaciones aluminio",
        mainGun: "23mm Type 23-3",
        penetration: "N/A",
        engine: "WP-13B x2",
        speed: 2335,
        weight: 17.0,
        year: 2004,
        characteristics: ["Radar Type 1471", "Misiles PL-12", "Interceptor puro", "Ala delta"]
    },

    // ========== SUECIA ==========
    {
        id: 47,
        name: "Strv 122B PLSS",
        type: "tanque",
        nation: "suecia",
        br: 11.7,
        era: "VII",
        crew: 4,
        armor: "Composite + Espaciada",
        mainGun: "120mm L/44",
        penetration: "510mm DM53",
        engine: "MTU MB-873 1500hp",
        speed: 68,
        weight: 62.5,
        year: 2002,
        characteristics: ["Armadura mejorada", "Sistema GALIX", "TI mejorado", "Munición DM53"]
    },
    {
        id: 48,
        name: "CV90120",
        type: "tanque",
        nation: "suecia",
        br: 11.3,
        era: "VII",
        crew: 3,
        armor: "Acero + Composite",
        mainGun: "120mm L/50",
        penetration: "450mm APFSDS",
        engine: "Scania DSI14 670hp",
        speed: 70,
        weight: 28.0,
        year: 2005,
        characteristics: ["Perfil bajo", "Movilidad excelente", "Cañón 120mm", "Sistema de visión"]
    },
    {
        id: 49,
        name: "JA37C Viggen",
        type: "avion",
        nation: "suecia",
        br: 11.3,
        era: "VII",
        crew: 1,
        armor: "Aleaciones ligeras",
        mainGun: "30mm KCA",
        penetration: "N/A",
        engine: "Volvo RM8B",
        speed: 2230,
        weight: 20.0,
        year: 1979,
        characteristics: ["Ala doble delta", "Canard", "Radar PS-46A", "Misiles RB71"]
    }
];